---
- hosts: all
  gather_facts: true
  vars_files:
    - default.config.yaml
  roles:
    - common
    # - geerlingguy.homebrew
    # - geerlingguy.mas
  # vars_prompt:
  #   - name: github_access_token
  #     prompt: Enter Github token
  #   - name: sudo_password
  #     prompt: Enter sudo password