---

- name: create .ssh dir
  file:
    path: "{{ ansible_facts['user_dir'] }}/.ssh"
    state: directory

- name: generate SSH keys manually
  command: ssh-keygen -q -f {{ ansible_facts['user_dir'] }}/.ssh/id_rsa -t rsa -C "ilya.shaisultanov@{{ ansible_facts['hostname'] }}" -N ""
  args:
    creates: "{{ ansible_facts['user_dir'] }}/.ssh/id_rsa*"

- name: Read SSH public key to authorize
  shell: cat {{ ansible_facts['user_dir'] }}/.ssh/id_rsa.pub
  register: ssh_pub_key

- name: Authorize key with GitHub
  local_action:
    module: github_key
    name: "{{ ansible_facts['hostname'] }} (added by Ansible)"
    token: '{{ github_access_token }}'
    pubkey: '{{ ssh_pub_key.stdout }}'

- name: Install packages
  homebrew:
    state: present
    name: "{{ brew_packages }}"
  when: lookup('env', 'SKIP_HOMEBREW') == ''

- name: Install cask apps
  homebrew_cask:
    accept_external_apps: yes
    # sudo_password: "{{ sudo_password }}"
    # greedy: yes
    # update_homebrew: yes
    # upgrade_all: yes
    state: present
    name: "{{ brew_cask_packages }}"
  when: lookup('env', 'SKIP_HOMEBREW_CASK') == ''

- name: Kill Zoom
  shell: "killall zoom.us ZoomOpener > /dev/null 2>&1 || true"
  ignore_errors: yes
  changed_when: false

- name: Clone dotfiles
  git:
    repo: git@github.com:diversario/dotfiles.git
    dest: "{{ ansible_facts['user_dir'] }}/.dotfiles"
    accept_hostkey: yes
    force: yes

- name: Install dotfiles
  command: "sh {{ ansible_facts['user_dir'] }}/.dotfiles/install.sh"
  args:
    chdir: "{{ ansible_facts['user_dir'] }}/.dotfiles"
    creates: "{{ ansible_facts['user_dir'] }}/.oh-my-zsh"

- name: Run macOS config
  shell: "bash {{ ansible_facts['user_dir'] }}/.dotfiles/configs/.osx"

- name: Install macOS App Store apps
  include_role:
    name: geerlingguy.mas
  when: lookup('env', 'SKIP_MAS') == ''
